python -m BNSReg.core.main fit \
    --model BNSReg.tasks.parameter_estimation.model_s4d_mse.LitModelS4DMSE \
    --model.cfg.d_input 2 \
    --model.cfg.d_output 1 \
    --model.cfg.d_model 4 \
    --model.cfg.d_state 4 \
    --model.cfg.n_layers 1 \
    --model.cfg.dropout 0.2 \
    --data BNSReg.dataloader.regression_loader.LitBNSDataRegression \
    --data.cfg.target_variables '["chirp_mass"]' \
    --data.cfg.observed_variables '["snr"]' \
    --data.cfg.train_file /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/bns_quick_test/train/sig_combined_train.h5 \
    --data.cfg.val_file /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/bns_quick_test/val/sig_combined_val.h5 \
    --data.cfg.test_file /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/bns_quick_test/test/sig_combined_test.h5 \
    --data.cfg.injected_data_key data \
    --data.cfg.train_batch_size 32 \
    --data.cfg.val_batch_size 32 \
    --data.cfg.test_batch_size 32 \
    --data.cfg.strain_frequency 256 \
    --data.cfg.window_begin 62.75 \
    --data.cfg.window_end 63 \
    --data.cfg.downsample_factor 2 \
    --data.cfg.num_workers 4 \
    --data.cfg.prefetch_factor 2 \
    --data.cfg.persistent_workers True \
    --trainer.fast_dev_run True