python -m BNSReg.core.main fit \
    --model BNSReg.tasks.parameter_estimation.model_s4d_mse.LitModelS4DGaussianNLLLoss \
    --model.model_cfg.d_input 2 \
    --model.model_cfg.d_output 2 \
    --model.model_cfg.d_model 4 \
    --model.model_cfg.d_state 4 \
    --model.model_cfg.n_layers 1 \
    --model.model_cfg.dropout 0.2 \
    --data BNSReg.dataloader.regression_loader.LitBNSDataRegression \
    --data.data_cfg.target_variables '["chirp_mass"]' \
    --data.data_cfg.observed_variables '["snr"]' \
    --data.data_cfg.train_file /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/bns_quick_test/train/sig_combined_train.h5 \
    --data.data_cfg.val_file /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/bns_quick_test/val/sig_combined_val.h5 \
    --data.data_cfg.test_file /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/bns_quick_test/test/sig_combined_test.h5 \
    --data.data_cfg.injected_data_key data \
    --data.data_cfg.train_batch_size 32 \
    --data.data_cfg.val_batch_size 32 \
    --data.data_cfg.test_batch_size 32 \
    --data.data_cfg.strain_frequency 256 \
    --data.data_cfg.window_begin 62.75 \
    --data.data_cfg.window_end 63 \
    --data.data_cfg.downsample_factor 2 \
    --data.data_cfg.num_workers 4 \
    --data.data_cfg.prefetch_factor 2 \
    --data.data_cfg.persistent_workers True \
    --trainer.fast_dev_run True