# lightning.pytorch==2.6.0

seed_everything: 20260223

trainer:
  accelerator: gpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null

  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: s4d_mse_snr_8_100_seq_length
      id: 59-to-63-d16-s4-l2
      save_dir: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/BNSReg/outputs

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        mode: min
        save_top_k: 1
        save_on_train_epoch_end: true
        filename: 's4d_mse_ckpt_{epoch:02d}'

    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss
        patience: 300
        mode: min
        verbose: true

    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch

  # ===== Training control =====
  fast_dev_run: false
  max_epochs: 2000
  min_epochs: 40
  max_steps: -1
  min_steps: null
  max_time: null

  # ===== Batch limits =====
  limit_train_batches: null     # float | int | null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null

  overfit_batches: 0.0          # float
  val_check_interval: null      # float | int | null
  check_val_every_n_epoch: 1    # int
  num_sanity_val_steps: null    # int | null
  log_every_n_steps: null       # int | null

  # ===== System =====
  enable_checkpointing: null    # bool | null
  enable_progress_bar: true     # bool
  enable_model_summary: null    # bool | null

  accumulate_grad_batches: 1    # int
  gradient_clip_val: null       # float | null
  gradient_clip_algorithm: null # str | null

  deterministic: null           # bool | null
  benchmark: null               # bool | null
  inference_mode: true          # bool
  use_distributed_sampler: true # bool

  profiler: null                # str | null
  detect_anomaly: false         # bool
  barebones: false              # bool
  plugins: null                 # str | list | null
  sync_batchnorm: false         # bool
  reload_dataloaders_every_n_epochs: 0  # int
  default_root_dir: null        # path | null
  enable_autolog_hparams: true  # bool
  model_registry: null          # str | null

# =========================
# Model
# =========================
model:
  class_path: BNSReg.tasks.parameter_estimation.model_s4d_mse.LitModelS4DMSE
  init_args:
    model_cfg:
      d_input: 1
      d_output: 1
      d_model: 16
      d_state: 4
      n_layers: 2
      dropout: 0.2

# =========================
# Data
# =========================
data:
  class_path: BNSReg.dataloader.regression_h1_loader.LitBNSDataRegressionH1
  init_args:
    data_cfg:
      # ===== Variables =====
      target_variables: ['chirp_mass']
      observed_variables: []

      # ===== Files =====
      train_file: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/bns_snr_8_100_powerlaw_256Hz_128s_100K/train/sig_combined_train.h5
      test_file: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/bns_snr_8_100_powerlaw_256Hz_128s_100K/test/sig_combined_test.h5
      val_file: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/bns_snr_8_100_powerlaw_256Hz_128s_100K/val/sig_combined_val.h5

      injected_data_key: injected_data
      waveform_data_key: null

      # ===== Signal properties =====
      strain_frequency: 256
      downsample_factor: 2
      strain_duration: 128
      coalescence_time: 127

      window_begin: 123
      window_end: 127

      # ===== Precision =====
      strain_precision: torch.float32
      variables_precision: torch.float32

      # ===== HDF5 caching =====
      rdcc_nbytes: 67108864   # int
      rdcc_nslots: 10007      # int
      rdcc_w0: 0.75           # float

      # ===== Batching =====
      train_batch_size: 32  # int (required)
      val_batch_size: 32    # int (required)
      test_batch_size: 32   # int (required)

      num_workers: 4        # int
      shuffle: true         # bool
      prefetch_factor: 64   # int
      persistent_workers: true # bool

# =========================
# Optimizer
# =========================
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-4   # float (required)

# =========================
# LR Scheduler
# =========================
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  init_args:
    T_0: 16     # int (required)
    T_mult: 1   # int
    eta_min: 1e-7 # float

# =========================
# Checkpoint loading
# =========================
ckpt_path: null  # path | null
weights_only: null  # bool | null