# lightning.pytorch==2.6.0

seed_everything: 20260215

trainer:
  accelerator: gpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null

  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: checks_s4d_gaussnll_snr_8_20
      id: chirp_mass_mse_25-55s_d256_s32_l4
      save_dir: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/BNSReg/outputs

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/mse/var_0
        mode: min
        save_top_k: 2
        save_on_train_epoch_end: true
        filename: 's4d_mse_ckpt_{epoch:02d}'

    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/mse/var_0
        patience: 200
        mode: min
        verbose: true

    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch

  # ===== Training control =====
  fast_dev_run: false
  max_epochs: 5000
  min_epochs: 100
  max_steps: -1
  min_steps: null
  max_time: null

  # ===== Batch limits =====
  limit_train_batches: null     # float | int | null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null

  overfit_batches: 0.0          # float
  val_check_interval: null      # float | int | null
  check_val_every_n_epoch: 1    # int
  num_sanity_val_steps: null    # int | null
  log_every_n_steps: 10       # int | null

  # ===== System =====
  enable_checkpointing: true    # bool | null
  enable_progress_bar: true     # bool
  enable_model_summary: true    # bool | null

  accumulate_grad_batches: 1    # int
  gradient_clip_val: null       # float | null
  gradient_clip_algorithm: null # str | null

  deterministic: null           # bool | null
  benchmark: null               # bool | null
  inference_mode: true          # bool
  use_distributed_sampler: true # bool

  profiler: null                # str | null
  detect_anomaly: false         # bool
  barebones: false              # bool
  plugins: null                 # str | list | null
  sync_batchnorm: false         # bool
  reload_dataloaders_every_n_epochs: 0  # int
  default_root_dir: null        # path | null
  enable_autolog_hparams: true  # bool
  model_registry: null          # str | null

# =========================
# Model
# =========================
model:
  class_path: BNSReg.tasks.parameter_estimation.model_s4d_mse.LitModelS4DMSE
  init_args:
    model_cfg:
      d_input: 2
      d_output: 1
      d_model: 256
      d_state: 32
      n_layers: 4
      dropout: 0.2
      dt_min: 0.001
      dt_max: 5
      lr: 5e-4

# =========================
# Data
# =========================
data:
  class_path: BNSReg.dataloader.regression_loader.LitBNSDataRegression
  init_args:
    data_cfg:
      # ===== Variables =====
      target_variables: ['chirp_mass']
      observed_variables: ['snr']
      normalize_variables: true
      normalize_range: [0.0, 1.0]

      # ===== Files =====
      train_file: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/checks/bns_snr_8_20_uniform_256Hz_80K/train/sig_combined_train.h5
      val_file:   /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/checks/bns_snr_8_20_uniform_256Hz_80K/val/sig_combined_val.h5
      test_file:  /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/ai4gw@cern/bns_snr_5_50_powerlaw_256Hz_80K_10K_100K/test/sig_combined_test.h5

      injected_data_key: whitened_injected
      sig_only_data_key: null
      bkg_only_data_key: null

      # ===== Signal properties =====
      strain_frequency: 256
      downsample_factor: 1
      strain_duration: 64
      coalescence_time: 63

      window_begin: 25
      window_end: 55

      # ===== Precision =====
      strain_precision: torch.float32
      variables_precision: torch.float32

      # ===== HDF5 caching =====
      rdcc_nbytes: 67108864   # int
      rdcc_nslots: 10007      # int
      rdcc_w0: 0.75           # float

      # ===== Batching =====
      train_batch_size: 128   # int (required)
      val_batch_size: 128     # int (required)
      test_batch_size: 128    # int (required)

      num_workers: 4        # int
      shuffle: true         # bool
      prefetch_factor: 4   # int
      persistent_workers: true # bool

# =========================
# Optimizer
# =========================
ckpt_path: null     # path | null
weights_only: null  # bool | null