python -m BNSReg.core.main fit \
    --model BNSReg.tasks.seq_denoise.conv_ae.LitModelConvAE \
    --model.cfg.n_layers 4 \
    --model.cfg.latent_channels 6 \
    --model.cfg.kernel_size 5 \
    --model.cfg.pool_stride 2 \
    --data BNSReg.dataloader.seq_encoder_loader.LitBNSDataSeqEncoder \
    --data.cfg.train_file /home/kyoon/Dev/seq_bns_snr_20_30_uniform_512Hz_10K/train/sig_combined_train.h5 \
    --data.cfg.val_file /home/kyoon/Dev/seq_bns_snr_20_30_uniform_512Hz_10K/val/sig_combined_val.h5 \
    --data.cfg.test_file /home/kyoon/Dev/seq_bns_snr_20_30_uniform_512Hz_10K/test/sig_combined_test.h5 \
    --data.cfg.train_batch_size 32 \
    --data.cfg.val_batch_size 32 \
    --data.cfg.test_batch_size 32 \
    --data.cfg.injected_data_key injected_data \
    --data.cfg.waveform_data_key signal_only_data \
    --data.cfg.strain_frequency 512 \
    --data.cfg.window_begin 62.75 \
    --data.cfg.window_end 63 \
    --data.cfg.downsample_factor 2