seed_everything: 20260225

trainer:
  accelerator: gpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null

  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: seq_denoise_snr_15_30_seq_0_55s
      id: h1_0_55s-n4-b4-h16
      save_dir: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/BNSReg/outputs
  
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss   # str
        mode: min           # str: min | max
        save_top_k: 1       # int
        save_on_train_epoch_end: true  # bool
        filename: 'conv_attn_ae_ap_ckpt_{epoch:02d}'  # str

    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/loss   # str
        patience: null      # int (required)
        mode: min           # str
        verbose: true       # bool

    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch   # str: step | epoch

  # ===== Training control =====
  fast_dev_run: false        # bool
  max_epochs: 500            # int
  min_epochs: 1              # int
  max_steps: -1              # int
  min_steps: null            # int | null
  max_time: null             # str | null

  # ===== Batch limits =====
  limit_train_batches: null     # float | int | null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null

  overfit_batches: 0.0          # float
  val_check_interval: null      # float | int | null
  check_val_every_n_epoch: 1    # int
  num_sanity_val_steps: null    # int | null
  log_every_n_steps: null       # int | null

  # ===== System =====
  enable_checkpointing: null    # bool | null
  enable_progress_bar: true     # bool
  enable_model_summary: null    # bool | null

  accumulate_grad_batches: 1    # int
  gradient_clip_val: null       # float | null
  gradient_clip_algorithm: null # str | null

  deterministic: null           # bool | null
  benchmark: null               # bool | null
  inference_mode: true          # bool
  use_distributed_sampler: true # bool

  profiler: null                # str | null
  detect_anomaly: false         # bool
  barebones: false              # bool
  plugins: null                 # str | list | null
  sync_batchnorm: false         # bool
  reload_dataloaders_every_n_epochs: 0  # int
  default_root_dir: null        # path | null
  enable_autolog_hparams: true  # bool
  model_registry: null          # str | null

# =========================
# Model
# =========================
model:
  class_path: BNSReg.tasks.seq_denoise.conv_ae.LitModelConvAttentionAEAP
  init_args:
    model_cfg:
      seq_length: 14080 # int (required)
      n_layers: 4       # int (required)
      base_dim: 4       # int (required)
      num_heads: 16     # int (required)
      dropout: 0.1      # float (0.0–1.0)

# =========================
# Data
# =========================
data:
  class_path: BNSReg.dataloader.seq_encoder_h1_loader.LitBNSDataSeqEncoderH1
  init_args:
    data_cfg:
      # ===== Files =====
      train_file: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/seq_bns_snr_15_30_uniform_512Hz_150K/train/sig_combined_train.h5
      test_file: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/seq_bns_snr_15_30_uniform_512Hz_150K/test/sig_combined_test.h5
      val_file: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/seq_bns_snr_15_30_uniform_512Hz_150K/val/sig_combined_val.h5

      injected_data_key: injected_data
      sig_only_data_key: sig_only_data
      bkg_only_data_key: null

      # ===== Signal properties =====
      strain_frequency: 512
      downsample_factor: 2
      strain_duration: 64
      coalescence_time: 63

      window_begin: 0
      window_end: 55

      # ===== Precision =====
      strain_precision: torch.float32
      variables_precision: torch.float32

      # ===== HDF5 caching =====
      rdcc_nbytes: 67108864   # int
      rdcc_nslots: 10007      # int
      rdcc_w0: 0.75           # float

      # ===== Batching =====
      train_batch_size: 256  # int (required)
      val_batch_size: 256    # int (required)
      test_batch_size: 256    # int (required)

      num_workers: 4         # int
      shuffle: true         # bool
      prefetch_factor: 4   # int
      persistent_workers: true # bool

# =========================
# Optimizer
# =========================
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 5e-4

# =========================
# LR Scheduler
# =========================
lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  init_args:
    T_0: 16     # int (required)
    T_mult: 1  # int
    eta_min: 5e-8 # float

# =========================
# Checkpoint loading
# =========================
ckpt_path: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/BNSReg/outputs/seq_denoise_snr_15_30_seq_0_55s/conv_attn_ae_ap_h16/checkpoints/conv_attn_ae_ap_ckpt_epoch=07.ckpt    # path | null
weights_only: null # bool | null