# lightning.pytorch==2.6.0

seed_everything: 20260413

trainer:
  accelerator: gpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null

  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: ai4gw@cern__s4d_psdloss_snr_10
      id: seq_denoise_psd_1-5s_d32_s32_l4
      save_dir: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/BNSReg/outputs

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/psd_loss
        mode: min
        save_top_k: 1
        save_on_train_epoch_end: true
        filename: 's4d_psd_ckpt_{epoch:02d}'

    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val/psd_loss
        patience: 60
        mode: min
        min_delta: 1e-4
        verbose: true

    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch

  # ===== Training control =====
  fast_dev_run: false
  max_epochs: 3000
  min_epochs: 100
  max_steps: -1
  min_steps: null
  max_time: null

  # ===== Batch limits =====
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null

  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 10

  # ===== System =====
  enable_checkpointing: null
  enable_progress_bar: true
  enable_model_summary: null

  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null

  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true

  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
  enable_autolog_hparams: true
  model_registry: null

# =========================
# Model
# =========================
model:
  class_path: BNSReg.tasks.seq_denoise.s4d_ae_psd.LitModelS4DAE_PSD
  init_args:
    cfg:
      d_input: 2
      d_output: 2
      d_model: 32
      d_state: 32
      n_layers: 4
      dropout: 0.2

# =========================
# Data
# =========================
data:
  class_path: BNSReg.dataloader.seq_encoder_loader.LitBNSDataSeqEncoder
  init_args:
    data_cfg:
      # ===== Files =====
      train_file: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/ai4gw@cern/bns_snr_10_256Hz_100K/train/sig_combined_train.h5
      test_file:  /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/ai4gw@cern/bns_snr_10_256Hz_100K/test/sig_combined_test.h5
      val_file:   /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/ai4gw@cern/bns_snr_10_256Hz_100K/val/sig_combined_val.h5

      injected_data_key: whitened_injected
      sig_only_data_key: whitened_signal

      # ===== Signal properties =====
      strain_frequency: 256
      downsample_factor: 1
      strain_duration: 64
      coalescence_time: 63

      window_begin: 0
      window_end: 4

      # ===== Precision =====
      strain_precision: torch.float32
      variables_precision: torch.float32

      # ===== HDF5 caching =====
      rdcc_nbytes: 67108864
      rdcc_nslots: 10007
      rdcc_w0: 0.75

      # ===== Batching =====
      train_batch_size: 256
      val_batch_size: 256
      test_batch_size: 256

      num_workers: 4
      shuffle: true
      prefetch_factor: 4
      persistent_workers: true

# =========================
# Optimizer
# =========================
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1e-4

# =========================
# LR Scheduler
# =========================
lr_scheduler:
  class_path: BNSReg.utils.schedulers.WarmupCosineAnnealingWarmRestarts
  init_args:
    warmup_epochs: 50
    T_0: 64
    T_mult: 2
    eta_min: 1e-8
    warmup_start_factor: 0.01

# =========================
# Checkpoint loading
# =========================
ckpt_path: null
weights_only: null
